// Mock data – used as fallback when DATABASE_URL is not configured.

const now = new Date();
const daysAgo = (d: number) => new Date(now.getTime() - d * 86_400_000);
const hoursAgo = (h: number) => new Date(now.getTime() - h * 3_600_000);

export const mockPlugins = [
  { id: 1, slug: "service-catalog",    name: "Service Catalog",       description: "Browse and manage all microservices and components in your platform.", icon: "BookOpen",      category: "observability", version: "1.2.0", enabled: true,  config: null, author: "Platform Team", createdAt: daysAgo(30), updatedAt: daysAgo(2)  },
  { id: 2, slug: "deployment-monitor", name: "Deployment Monitor",    description: "Real-time deployment status and history across all environments.",      icon: "Activity",      category: "ci-cd",         version: "2.0.1", enabled: true,  config: null, author: "Platform Team", createdAt: daysAgo(28), updatedAt: daysAgo(1)  },
  { id: 3, slug: "ai-assistant",       name: "AI Assistant",          description: "AI-powered DevOps assistant for troubleshooting and log analysis.",      icon: "Bot",           category: "ai",            version: "1.0.0", enabled: true,  config: null, author: "Platform Team", createdAt: daysAgo(14), updatedAt: daysAgo(0)  },
  { id: 4, slug: "onboarding",         name: "Onboarding Workflow",   description: "Scaffold new projects from curated templates with one click.",           icon: "Rocket",        category: "developer-exp", version: "1.1.0", enabled: true,  config: null, author: "Platform Team", createdAt: daysAgo(20), updatedAt: daysAgo(5)  },
  { id: 5, slug: "metrics",            name: "Developer Metrics",     description: "DORA and SPACE framework dashboards for engineering effectiveness.",      icon: "BarChart3",     category: "analytics",     version: "1.3.0", enabled: true,  config: null, author: "Platform Team", createdAt: daysAgo(25), updatedAt: daysAgo(3)  },
  { id: 6, slug: "marketplace",        name: "Plugin Marketplace",    description: "Discover and enable community plugins to extend your platform.",          icon: "Store",         category: "platform",      version: "1.0.0", enabled: true,  config: null, author: "Platform Team", createdAt: daysAgo(10), updatedAt: daysAgo(1)  },
];

export const mockServices = [
  { id: 1,  name: "API Gateway",         slug: "api-gateway",         description: "Central entry point for all client requests with rate limiting and auth.", owner: "Alice Chen",   team: "Platform",   language: "Go",         framework: "Gin",        repoUrl: "https://github.com/example/api-gateway",      status: "healthy",  tier: "critical", tags: ["gateway","auth"],        createdAt: daysAgo(90), updatedAt: hoursAgo(2)  },
  { id: 2,  name: "User Service",        slug: "user-service",        description: "Handles user registration, profiles, and authentication flows.",           owner: "Bob Kim",     team: "Identity",   language: "TypeScript", framework: "NestJS",     repoUrl: "https://github.com/example/user-service",     status: "healthy",  tier: "critical", tags: ["users","auth"],          createdAt: daysAgo(85), updatedAt: hoursAgo(5)  },
  { id: 3,  name: "Payment Service",     slug: "payment-service",     description: "Processes payments and manages transaction records.",                      owner: "Carol Davis",  team: "Payments",   language: "Java",       framework: "Spring Boot",repoUrl: "https://github.com/example/payment-service",  status: "degraded", tier: "critical", tags: ["payments","finance"],     createdAt: daysAgo(80), updatedAt: hoursAgo(1)  },
  { id: 4,  name: "Notification Hub",    slug: "notification-hub",    description: "Sends emails, push notifications, and SMS via multiple providers.",        owner: "Dan Lee",      team: "Platform",   language: "Python",     framework: "FastAPI",    repoUrl: "https://github.com/example/notification-hub", status: "healthy",  tier: "high",     tags: ["notifications","email"], createdAt: daysAgo(70), updatedAt: hoursAgo(8)  },
  { id: 5,  name: "Search Service",      slug: "search-service",      description: "Full-text search powered by Elasticsearch for products and content.",      owner: "Eva Martinez", team: "Discovery",  language: "TypeScript", framework: "Express",    repoUrl: "https://github.com/example/search-service",   status: "healthy",  tier: "high",     tags: ["search","elasticsearch"],createdAt: daysAgo(65), updatedAt: hoursAgo(12) },
  { id: 6,  name: "Analytics Pipeline",  slug: "analytics-pipeline",  description: "Ingests and processes event streams for business intelligence.",           owner: "Frank Wu",     team: "Data",       language: "Python",     framework: "Apache Flink",repoUrl:"https://github.com/example/analytics",        status: "healthy",  tier: "medium",   tags: ["analytics","kafka"],     createdAt: daysAgo(60), updatedAt: hoursAgo(4)  },
  { id: 7,  name: "Inventory Service",   slug: "inventory-service",   description: "Tracks stock levels and manages warehouse operations.",                    owner: "Grace Park",   team: "Commerce",   language: "Rust",       framework: "Actix",      repoUrl: "https://github.com/example/inventory-service",status: "healthy",  tier: "high",     tags: ["inventory","commerce"],  createdAt: daysAgo(55), updatedAt: hoursAgo(6)  },
  { id: 8,  name: "Recommendation ML",   slug: "recommendation-ml",   description: "ML-based recommendation engine for personalised content and products.",    owner: "Henry Zhang",  team: "Data",       language: "Python",     framework: "PyTorch",    repoUrl: "https://github.com/example/recommendation-ml",status: "down",   tier: "medium",   tags: ["ml","recommendations"],  createdAt: daysAgo(40), updatedAt: hoursAgo(0)  },
  { id: 9,  name: "Media CDN Worker",    slug: "media-cdn-worker",    description: "Resizes, transcodes, and distributes media assets across CDN edges.",      owner: "Iris Tanaka",  team: "Platform",   language: "Go",         framework: "Fiber",      repoUrl: "https://github.com/example/media-cdn",        status: "healthy",  tier: "medium",   tags: ["media","cdn"],           createdAt: daysAgo(35), updatedAt: hoursAgo(10) },
  { id: 10, name: "Config Service",      slug: "config-service",      description: "Centralised dynamic configuration and feature flag management.",           owner: "Jack Lin",     team: "Platform",   language: "TypeScript", framework: "Fastify",    repoUrl: "https://github.com/example/config-service",   status: "healthy",  tier: "high",     tags: ["config","feature-flags"],createdAt: daysAgo(30), updatedAt: hoursAgo(3)  },
];

export const mockDeployments = [
  { id: 1,  serviceId: 1,  version: "v2.4.1", environment: "production",  status: "success",    triggeredBy: "alice.chen",   commitHash: "a3f2c91", commitMessage: "fix: resolve rate limiting edge case on burst traffic",       duration: 42,  logs: null, createdAt: hoursAgo(1),   updatedAt: hoursAgo(1)   },
  { id: 2,  serviceId: 3,  version: "v1.9.0", environment: "production",  status: "failed",     triggeredBy: "carol.davis",  commitHash: "b8d1e45", commitMessage: "feat: add PayPal payment provider integration",               duration: 67,  logs: null, createdAt: hoursAgo(2),   updatedAt: hoursAgo(2)   },
  { id: 3,  serviceId: 5,  version: "v3.1.2", environment: "staging",     status: "success",    triggeredBy: "eva.martinez", commitHash: "c5a9f23", commitMessage: "perf: add Redis caching layer to search results",             duration: 38,  logs: null, createdAt: hoursAgo(3),   updatedAt: hoursAgo(3)   },
  { id: 4,  serviceId: 2,  version: "v4.0.0", environment: "production",  status: "deploying",  triggeredBy: "bob.kim",      commitHash: "d2b7e11", commitMessage: "feat: OAuth 2.0 PKCE flow for mobile clients",               duration: null,logs: null, createdAt: hoursAgo(0),   updatedAt: hoursAgo(0)   },
  { id: 5,  serviceId: 8,  version: "v0.9.5", environment: "development", status: "failed",     triggeredBy: "henry.zhang",  commitHash: "e6c3d88", commitMessage: "experiment: new collaborative filtering algorithm v2",        duration: 120, logs: null, createdAt: hoursAgo(4),   updatedAt: hoursAgo(4)   },
  { id: 6,  serviceId: 4,  version: "v2.2.3", environment: "production",  status: "success",    triggeredBy: "dan.lee",      commitHash: "f1a5b67", commitMessage: "fix: retry logic for failed SMS deliveries",                  duration: 29,  logs: null, createdAt: hoursAgo(6),   updatedAt: hoursAgo(6)   },
  { id: 7,  serviceId: 7,  version: "v1.5.1", environment: "staging",     status: "success",    triggeredBy: "grace.park",   commitHash: "g9e2c34", commitMessage: "feat: bulk stock update API endpoint",                       duration: 51,  logs: null, createdAt: hoursAgo(8),   updatedAt: hoursAgo(8)   },
  { id: 8,  serviceId: 10, version: "v2.0.0", environment: "production",  status: "success",    triggeredBy: "jack.lin",     commitHash: "h4d6f12", commitMessage: "feat: real-time config push via WebSocket",                   duration: 33,  logs: null, createdAt: hoursAgo(10),  updatedAt: hoursAgo(10)  },
  { id: 9,  serviceId: 6,  version: "v1.8.0", environment: "staging",     status: "success",    triggeredBy: "frank.wu",     commitHash: "i7b3a45", commitMessage: "perf: Kafka consumer group rebalancing optimisation",         duration: 44,  logs: null, createdAt: hoursAgo(12),  updatedAt: hoursAgo(12)  },
  { id: 10, serviceId: 9,  version: "v1.3.2", environment: "production",  status: "success",    triggeredBy: "iris.tanaka",  commitHash: "j2e8c67", commitMessage: "fix: HEIC to JPEG conversion memory leak",                   duration: 27,  logs: null, createdAt: hoursAgo(14),  updatedAt: hoursAgo(14)  },
  { id: 11, serviceId: 1,  version: "v2.4.0", environment: "production",  status: "success",    triggeredBy: "alice.chen",   commitHash: "k5f1b23", commitMessage: "feat: add gRPC-Web support for browser clients",              duration: 48,  logs: null, createdAt: daysAgo(1),    updatedAt: daysAgo(1)    },
  { id: 12, serviceId: 3,  version: "v1.8.5", environment: "staging",     status: "success",    triggeredBy: "carol.davis",  commitHash: "l8a4d56", commitMessage: "refactor: extract payment validation into shared library",     duration: 35,  logs: null, createdAt: daysAgo(1),    updatedAt: daysAgo(1)    },
  { id: 13, serviceId: 2,  version: "v3.9.2", environment: "production",  status: "rolled_back",triggeredBy: "bob.kim",      commitHash: "m3c7e89", commitMessage: "feat: social login with Apple ID (reverted – token issue)",    duration: 95,  logs: null, createdAt: daysAgo(2),    updatedAt: daysAgo(2)    },
  { id: 14, serviceId: 5,  version: "v3.1.1", environment: "production",  status: "success",    triggeredBy: "eva.martinez", commitHash: "n6b2a12", commitMessage: "fix: stemming for non-English locales",                       duration: 31,  logs: null, createdAt: daysAgo(2),    updatedAt: daysAgo(2)    },
  { id: 15, serviceId: 8,  version: "v0.9.4", environment: "staging",     status: "failed",     triggeredBy: "henry.zhang",  commitHash: "o1d5f34", commitMessage: "feat: A/B test personalisation model switch",                 duration: 88,  logs: null, createdAt: daysAgo(3),    updatedAt: daysAgo(3)    },
];

export const mockTemplates = [
  { id: 1, name: "Next.js Full-Stack",     description: "Production-ready Next.js app with TypeScript, Tailwind, Prisma, and NextAuth.",       language: "TypeScript", framework: "Next.js",      category: "web",       features: ["SSR","Auth","DB","Testing"],       popularity: 94, createdAt: daysAgo(60) },
  { id: 2, name: "Go Microservice",        description: "Lightweight Go service with Gin, structured logging, Prometheus metrics, and Docker.", language: "Go",         framework: "Gin",          category: "backend",   features: ["gRPC","Metrics","Docker","CI"],    popularity: 87, createdAt: daysAgo(55) },
  { id: 3, name: "Python FastAPI",         description: "Async REST API with FastAPI, SQLAlchemy, Alembic migrations, and OpenAPI docs.",       language: "Python",     framework: "FastAPI",      category: "backend",   features: ["Async","ORM","Docs","Auth"],       popularity: 91, createdAt: daysAgo(50) },
  { id: 4, name: "React SPA + Vite",       description: "Modern React SPA with Vite, TanStack Query, Zustand, and Vitest.",                     language: "TypeScript", framework: "React",        category: "web",       features: ["HMR","Testing","State","Routes"],  popularity: 82, createdAt: daysAgo(45) },
  { id: 5, name: "NestJS Enterprise",      description: "Scalable NestJS API with TypeORM, JWT auth, role guards, and Swagger.",                language: "TypeScript", framework: "NestJS",       category: "backend",   features: ["DI","Auth","ORM","Swagger"],       popularity: 78, createdAt: daysAgo(40) },
  { id: 6, name: "Data Pipeline",          description: "Python ETL pipeline with Apache Airflow, dbt, and Great Expectations for DQ.",         language: "Python",     framework: "Apache Airflow",category: "data",     features: ["ETL","Scheduling","DQ","Docs"],    popularity: 65, createdAt: daysAgo(35) },
  { id: 7, name: "Rust gRPC Service",      description: "High-performance Rust service with Tonic gRPC, Tokio async runtime, and Prometheus.",  language: "Rust",       framework: "Actix + Tonic",category: "backend",  features: ["gRPC","Async","Metrics","Docker"], popularity: 59, createdAt: daysAgo(30) },
  { id: 8, name: "Serverless Function",    description: "AWS Lambda function with TypeScript, CDK infrastructure-as-code, and X-Ray tracing.",  language: "TypeScript", framework: "AWS Lambda",   category: "cloud",     features: ["CDK","Tracing","CI/CD","IaC"],     popularity: 73, createdAt: daysAgo(20) },
];
